### ISSUE TITLE
Can you offer a more detailed example for the Redux implementation?

### ISSUE THREAD

**Issue by TheBigElectron** [zaromev/react-native-connection-info#7]

**Comment by bigamasta** [comment]
For Redux: This worked for me @TheBigElectron 

```
import { withConnection } from 'react-native-connection-info'
withConnection(connect(...)(App))
```

**Comment by spacebattery** [comment]
Hey @TheBigElectron, Sorry I haven't had the time to reply.
I assume that you are now clear on how to use it with redux?
Will be closing this soon. 🙂

Thanks @bigamasta for replying with an example.
