### ISSUE TITLE
Using it with http request

### ISSUE THREAD

**Issue by amitbravo** [zaromev/react-native-connection-info#9]
I want to use it every time I make a http request , it returns true , then proceed to the request else display an offline message .
How can I perform like this ?

import React, { Component }  from 'react';
import {
  Text,
  View,
} from 'react-native';
import { withConnection, connectionShape } from 'react-native-connection-info';
// Sudo 
if true > axios.get
else 'internet is not established'
// Sudo ends.

**Comment by spacebattery** [comment]
You can wrap your component using `withConnection` just like in the example, and call your http request in your component's `componentDidMount` method. 
You can retrieve the `connection` object here and use it to decide whether there's an internet connection or not.
